#%RAML 1.0 NamedExample
{
  "errorCode": "401",
  "errorMessage": "Unauthorized, The client_id or client_secret are not valid or the client does not have access.",
  "transactionId": "dd872282-abbf-98c2-8c12-f18jjb98988b",
  "timeStamp": "2023-08-11T15:27:49.274Z"
}