#%RAML 1.0 NamedExample
{
  "errorCode": "415",
  "errorMessage": "The server is refusing to the request because it is not in a format supported by the target resource.",
  "transactionId": "dd872282-abbf-98c2-8c12-f18jjb98988b",
  "timeStamp": "2023-08-11T15:27:49.274Z"
}