#%RAML 1.0 NamedExample
{
  "errorCode": "500",
  "errorMessage": "The server was unable to process the request due to an internal error",
  "transactionId": "dd872282-abbf-98c2-8c12-f18jjb98988b",
  "timeStamp": "2019-08-11T15:27:49.274Z"
}