#%RAML 1.0 NamedExample
{
  "errorCode": "406",
  "errorMessage": "The requested resource cannot generate acceptable content according to the Accept headers sent in the request.",
  "transactionId": "dd872282-abbf-98c2-8c12-f18jjb98988b",
  "timeStamp": "2023-08-11T15:27:49.274Z"
}