#%RAML 1.0 NamedExample
{
  "errorCode": "401",
  "errorMessage": "Unauthorized, The access token is invalid or expired.",
  "transactionId": "dd872282-abbf-98c2-8c12-f18jjb98988b",
  "timeStamp": "2023-08-11T15:27:49.274Z"
}