#%RAML 1.0 NamedExample
{
  "errorCode": "405",
  "errorMessage": "The target resource does not support the requested method",
  "transactionId": "dd872282-abbf-98c2-8c12-f18jjb98988b",
  "timeStamp": "2023-08-11T15:27:49.274Z"
}