#%RAML 1.0 Trait

headers:
  client_id:
    type: string
  client_secret:
    type: string

responses:
  401:
    body:
      application/json:
        type: !include ../dataTypes/ErrorResponseType.raml
        example: !include ../examples/Return401Example.raml
  429:
    body:
      application/json:
        type: !include ../dataTypes/ErrorResponseType.raml
        example: !include ../examples/Return429Example.raml
  503:
    body:
      application/json:
        type: !include ../dataTypes/ErrorResponseType.raml
        example: !include ../examples/Return503Example.raml