#%RAML 1.0 Trait
usage: Apply trait to the /ping endpoint of APIs

responses:
  200:
    body:
      application/json:
        type: !include ../dataTypes/PingResponseType.raml
        example: !include ../examples/PingResponseExample.raml
