%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo({
  "patients": [
    {
      "patientid": 4,
      "firstname": "Trisha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": "2023-08-16T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 5,
      "hospitalreview": "Excellent Facility",
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 16,
      "firstname": "shreya",
      "lastname": "Sharma",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-17T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 2,
      "hospitalreview": "Excellent Facility",
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 9,
      "firstname": "Shriya",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 11,
      "firstname": "Prerna",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 12,
      "firstname": "nanaa",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 13,
      "firstname": "nanaa",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 14,
      "firstname": "kiki",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": "2023-08-14T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 25,
      "firstname": "kiki",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 26,
      "firstname": "kiki",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 15,
      "firstname": "Priya",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-17T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 2,
      "hospitalreview": "bad Facility",
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 27,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 28,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 19,
      "firstname": "kiki",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 34,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 10,
      "firstname": "Shriya",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": "2023-08-22T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 8,
      "firstname": "Priya",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-14T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 2,
      "hospitalreview": "bad Facility",
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 3,
      "firstname": "Lata",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-14T15:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 5,
      "hospitalreview": "Excellent and best Facility",
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Discharged"
    },
    {
      "patientid": 18,
      "firstname": "Priya",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 37,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 38,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 44,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 47,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 48,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 54,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 57,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 58,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 64,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 67,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 68,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 74,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 77,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 78,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 84,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 87,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 88,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 94,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 97,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 98,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 104,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 107,
      "firstname": "kikii",
      "lastname": "choubey",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 108,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 109,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 112,
      "firstname": "Priya",
      "lastname": "Chopra",
      "address": {
        "area": "South Extension",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110049"
      },
      "disease": "None",
      "gender": "Female",
      "admitdate": "2023-08-19T16:10:00Z",
      "dischargedate": "",
      "phonenumber": 1312345678,
      "weight": 55,
      "medicaldetails": "None",
      "bloodtype": "O-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Quick service",
      "hospitalname": "Carewell Clinic",
      "age": 30,
      "email": "priya@example.com",
      "height": 163,
      "status": "Admitted"
    },
    {
      "patientid": 115,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 118,
      "firstname": "Reema",
      "lastname": "Sharma",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "reema@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 119,
      "firstname": "Shreya",
      "lastname": "Sharma",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "reema@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 120,
      "firstname": "Misha",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "CG",
        "country": "India",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": "2023-08-20T10:00:00Z",
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Great service",
      "hospitalname": "City Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 121,
      "firstname": "Aryan",
      "lastname": "Verma",
      "address": {
        "area": "Green Park",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110016"
      },
      "disease": "Hypertension",
      "gender": "Male",
      "admitdate": "2023-08-15T11:30:00Z",
      "dischargedate": "2023-08-22T09:15:00Z",
      "phonenumber": 1324405522,
      "weight": 78,
      "medicaldetails": "Ongoing medication",
      "bloodtype": "A-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Satisfied overall",
      "hospitalname": "Metro Health Center",
      "age": 42,
      "email": "aryan@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 124,
      "firstname": "Priya",
      "lastname": "Chopra",
      "address": {
        "area": "South Extension",
        "city": "Delhi",
        "state": "DL",
        "country": "India",
        "pin": "110049"
      },
      "disease": "None",
      "gender": "Female",
      "admitdate": "2023-08-19T16:10:00Z",
      "dischargedate": "",
      "phonenumber": 1312345678,
      "weight": 55,
      "medicaldetails": "None",
      "bloodtype": "O-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Quick service",
      "hospitalname": "Carewell Clinic",
      "age": 30,
      "email": "priya@example.com",
      "height": 163,
      "status": "Admitted"
    },
    {
      "patientid": 127,
      "firstname": "Sameer",
      "lastname": "Desai",
      "address": {
        "area": "Baner",
        "city": "Pune",
        "state": "MH",
        "country": "India",
        "pin": "411045"
      },
      "disease": "Heart Condition",
      "gender": "Male",
      "admitdate": "2023-08-18T10:45:00Z",
      "dischargedate": "2023-08-25T14:00:00Z",
      "phonenumber": 1365432109,
      "weight": 82,
      "medicaldetails": "Medication regimen",
      "bloodtype": "AB-",
      "hospitalid": "1",
      "hospitalrating": 4,
      "hospitalreview": "Expert cardiologists",
      "hospitalname": "HeartCare Hospital",
      "age": 45,
      "email": "sameer@example.com",
      "height": 175,
      "status": "Admitted"
    },
    {
      "patientid": 134,
      "firstname": "Shreya",
      "lastname": "Sharma",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "reema@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 136,
      "firstname": "Shreya",
      "lastname": "Sharma",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Female",
      "admitdate": "2023-08-16T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "reema@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 147,
      "firstname": "niharika",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 148,
      "firstname": "niharika",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    },
    {
      "patientid": 149,
      "firstname": "niharika",
      "lastname": "Saxena",
      "address": {
        "area": "Smriti Nagar",
        "city": "Bhilai",
        "state": "cg",
        "country": "india",
        "pin": "490020"
      },
      "disease": "Diabetes",
      "gender": "Male",
      "admitdate": "2023-08-14T15:00:00Z",
      "dischargedate": null,
      "phonenumber": 1307744195,
      "weight": 80,
      "medicaldetails": "Regular check-ups",
      "bloodtype": "O+",
      "hospitalid": "1",
      "hospitalrating": null,
      "hospitalreview": null,
      "hospitalname": "ABC Hospital",
      "age": 35,
      "email": "misha@example.com",
      "height": 180,
      "status": "Admitted"
    }
  ]
})